### ISSUE TITLE
Jenkins issue

### ISSUE THREAD

**Issue by gitvipul** [Azure/kubernetes-hackfest#19]
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default/api/v1/namespaces/default/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "aks-hackfest-5xt6m-9d308" is forbidden: error looking up service account default/jenkins-jenkins: serviceaccount "jenkins-jenkins" not found.
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:766)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:335)
        at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:105)
        at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:292)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by dstrebel** [comment]
Will check why the service-name is different from env to env, Changing the following line in the Jenkinsfile should make it work for now.

serviceAccountName: jenkins-jenkins -> serviceAccountName: jenkins

**Comment by chzbrgr71** [comment]
trying this for now. don't do this. `kubectl create clusterrolebinding jenkinsadmin --clusterrole=cluster-admin --serviceaccount=default:jenkins-jenkins`

**Comment by chzbrgr71** [comment]
Three things that are causing problems here. Still waiting to see if this works.

- helm suddenly started naming resources as `jenkins` instead of `jenkins-jenkins` this included the serviceaccount
- in the `jenkinsfile` pipeline script on line 21, it sets the sa. Now this needs to be `jenkins` https://github.com/Azure/kubernetes-hackfest/blob/master/labs/cicd-automation/jenkins/Jenkinsfile#L21 
- since they are forking the repo from the original source, the service-trakcer-ui chart has the wrong ACR name in the `values.yaml` They had fixed this earlier, but in this lab, they are working from a new copy and the deploy then fails. Need to add instructions for this
